name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.0'  # make sure this matches your local Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build and test
      run: |
        bundle exec jekyll build
        bundle exec jekyll serve & sleep 10; kill $!

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
